function [] = init_labels()
%INIT_LABELS Initializes some useful labels

global GIVE_MODE_DEFAULT GIVE_MODE_DUALFREQ GIVE_MODE_NSEMODEL
global OUTPUT_BIAS_LABEL OUTPUT_STD_LABEL OUTPUT_VAR_LABEL
global OUTPUT_IONO_LABEL OUTPUT_CLKEPH_LABEL


GIVE_MODE_DEFAULT = 0;
GIVE_MODE_DUALFREQ = 1;
GIVE_MODE_NSEMODEL = 2;

OUTPUT_BIAS_LABEL = 'Bias';
OUTPUT_STD_LABEL = 'STD';
OUTPUT_VAR_LABEL = 'Variance';

OUTPUT_IONO_LABEL = 'Iono';
OUTPUT_CLKEPH_LABEL = 'Clock+Eph';


end

